import { zipObject } from 'lodash';

const ACTION_TYPES = [
  'GET_SAMPLE_USER_DATA_ATTEMPTED',
  'GET_SAMPLE_USER_DATA_SUCCEEDED',
  'GET_SAMPLE_USER_DATA_FAILED',

  'GET_SAMPLE_PHOTO_DATA_ATTEMPTED',
  'GET_SAMPLE_PHOTO_DATA_SUCCEEDED',
  'GET_SAMPLE_PHOTO_DATA_FAILED'
];

export default zipObject(ACTION_TYPES, ACTION_TYPES);